### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by xas** [xas/RatioMaster.Core#6]
Refactoring project consists on two phases :  

- [x] Rewrite code in a simplified way  
- [x] Refactor with better solution  

---  

### Phase 1 : Rewriting  
Improving code with existing solution. The first step is to improve the actual code without looking for deep refactoring.  
- [x] BitTorrent folder  
- [ ] BytesRoads folder  
- [x] Forms code-behind  
- [x] Others classes  

### Phase 2 : Refactoring  
- [x] TorrentManager  
- [x] NetworkManager
